name: RankSystem
version: 1.0
main: me.projectx.RankSystem.Main
commands:
  points:
    description: Add or remove points
  getRank:
    description: Gets a designated player's rank
  getPoints:
    description: Gets a designated player's points